version: '3.1'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  rest-service:
    depends_on:
      - redis
    image: jsainz/spring-day-native
    environment:
      - REDIS_URI=redis://redis:6379
      - APP_SCRIPTSFOLDER=.
    ports:
      - "8080:8080"
